In [3]:
import numpy as np

In [7]:
l1 = np.arange(1,28)
l1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [21]:
l1 = np.arange(1,28).reshape((3,3,3))
l1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [18]:
l1 = np.arange(1,5).reshape((2,2))
l1

array([[1, 2],
       [3, 4]])

In [19]:
l1 = np.arange(1,28).reshape((3,3,3))
l1[l1 % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [29]:
l1 = np.random.randint(35)
print(l1)

6


In [30]:
l1 = np.random.randn(3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[-7.87178802e-01 -1.95509056e-01  1.62178042e+00]
  [-1.00397419e+00  6.75496270e-01 -1.47658949e-03]
  [-1.19083703e+00 -1.63331329e+00 -1.26792685e+00]]

 [[ 7.35329245e-02  1.39226308e+00 -3.37701707e-01]
  [-2.25628263e-01  1.64173647e+00 -2.13596038e-01]
  [-6.28373964e-02  7.48906533e-01  1.42269662e+00]]

 [[ 1.33545457e+00 -1.53365554e+00 -3.06262864e-02]
  [ 5.10333086e-01  3.30509429e-01  1.58498463e-01]
  [ 5.89890121e-02 -2.91443748e-01  5.31769456e-01]]]
Diminsion: 3
Type: float64
Size: 27
Itemsize: 8
Shape: (3, 3, 3)


In [31]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
a[[1,2,0]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


[29 10 29 29 51 36 10 47  4 31 51 14  1 38 52 25 53 38 49 52]


array([ 1,  4, 10, 14, 25, 29, 31, 36, 38, 47, 49, 51, 52, 53])